# Generated by Django 3.1.5 on 2021-02-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(blank=True, max_length=100, null=True)),
                ('market_special', models.CharField(blank=True, max_length=150, null=True)),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
