# Generated by Django 3.1.5 on 2021-02-09 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_auto_20210209_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Currently unavailable', 'Currently unavailable'), ('Currently available', 'Currently available')], max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market', to='markets.market')),
            ],
        ),
    ]
