# Generated by Django 3.1.5 on 2021-02-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_marketlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketlist',
            old_name='user',
            new_name='market',
        ),
    ]
