# Generated by Django 3.1.5 on 2021-01-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0005_auto_20210126_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='toy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
